<a href="https://colab.research.google.com/github/hojun-code/2026-BDA/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[3.66528877e-315, 0.00000000e+000, 6.79038055e-310],
       [6.79038056e-310, 6.79038056e-310, 6.79038056e-310]])

In [2]:
a = np.ndarray((3, 2), dtype=int)
a

array([[      741862706,               0],
       [137438832488080, 137438832527536],
       [137438832527600, 137438832527664]])

In [3]:
a = np.ndarray((3, 2), int)
a

array([[         180516,               0],
       [137438973349360, 137438973271216],
       [137438973349936, 137438973349424]])

In [4]:
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [7]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [8]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [9]:
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [10]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

In [11]:
print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [12]:
print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [13]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [16]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [18]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [19]:
print( (3-2) / (50-1))

0.02040816326530612


In [20]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [21]:
print( (3-2) / 50)

0.02


In [22]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [23]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [24]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [25]:
a.dtype

dtype('float64')

In [26]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [27]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [28]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [32]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [33]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [35]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [36]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [37]:
np.full([2, 3], (1, 2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [38]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [39]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [40]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [41]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [42]:
np.empty([2, 3], dtype=int)

array([[          745798831,                   0, 3565725009265557504],
       [       258394040444,   23406936108351372,     137438830822656]])

In [43]:
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [46]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [47]:
a = np.arange(3)
a

array([0, 1, 2])

In [48]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [49]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [51]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [52]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [53]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [54]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [55]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

In [56]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [57]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [58]:
a @ b

array([[12,  6],
       [12,  6]])

In [59]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [60]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [61]:
print(np.matmul(a, b))
print(np.matmul(b, a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [62]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [63]:
a.sum()

np.int64(46)

In [64]:
a.sum(axis=0)

array([16, 30])

In [65]:
a.sum(axis=1)

array([30, 13,  3])

In [66]:
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [67]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [68]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [69]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [70]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [71]:
a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [72]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [73]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [74]:
np.add(a, b)

array([ 3,  6, 11])

In [75]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [76]:
np.power(a, b)

array([ 1, 16, 81])

In [77]:
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [78]:
print(a[3])
print(a[-2])

9
64


In [79]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [80]:
a[8:2:-2]

array([64, 36, 16])

In [81]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [82]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [83]:
a[::-2]

array([81, 49, 25,  9,  1])

In [84]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [85]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [86]:
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [87]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

In [88]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [89]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [90]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [91]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [92]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [93]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [94]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [95]:
a[, 1]

SyntaxError: invalid syntax (3063698125.py, line 1)

In [96]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [97]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [98]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [99]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [100]:
a[2, 4]

np.int64(16)

In [101]:
a[2][4]

np.int64(16)

In [102]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [103]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [104]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [105]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [106]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [107]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [108]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [109]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [111]:
a[:, 1, 1]

array([ 5, 17])

In [112]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [113]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [114]:
a[1, ..., 1]

array([13, 17, 21])

In [115]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [118]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [121]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [122]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [123]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [124]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [125]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [126]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [127]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [128]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [129]:
x = np.array([[7, 8, 9]])

In [130]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [131]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [132]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [133]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [134]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [135]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [136]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [137]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [138]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [139]:
org

array([  0,   1, 200,   3,   4])

In [140]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [141]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [142]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [143]:
org

array([0, 1, 2, 3, 4])

In [144]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [145]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [146]:
print(x.base)

None


In [147]:
y.base

array([0, 1, 2, 3, 4, 5])

In [148]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [149]:
c = z.copy()
print(c.base)

None


In [150]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [151]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [152]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [153]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [154]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [155]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
b = a
b is a

True

In [157]:
print(id(a))
print(id(b))

137438824468272
137438824468272


In [158]:
print(a.base)
print(b.base)

None
None


In [159]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [160]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [161]:
print(id(a))
print(id(c))

137438824468272
137438824468560


In [162]:
print(c.base)

None


In [163]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [164]:
print(id(a))
print(id(v))

137438824468272
137438824724496


In [165]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [166]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [167]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [168]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [169]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
y = np.arange(-1, 2)
y

array([-1,  0,  1])

In [171]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [172]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [173]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [174]:
y = np.arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [175]:
np.set_printoptions(precision=2)

In [176]:
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [177]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [178]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [179]:
y = np.arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [180]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [181]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [182]:
x = np.arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [183]:
y = np.arange(1, 3)
y

array([1, 2])

In [184]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [185]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [186]:
x = np.array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [187]:
np.newaxis is None

True

In [188]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [189]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [190]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [191]:
a.shape

(4, 1)

In [192]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [193]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [194]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [195]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [196]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [198]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [199]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [200]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [201]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [202]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [203]:
x[0, 1]

np.int64(1)

In [204]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [205]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [206]:
x[[0], [1]]

array([1])

In [207]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [208]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [209]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [210]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [211]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [212]:
x[[1, 3], [2, 2]]

array([10, 26])

In [213]:
x[[1, 3], [2]]

array([10, 26])

In [214]:
x[[1, 3], 2]

array([10, 26])

In [215]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [216]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [217]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [218]:
x[np.array([0, 2, 4]), :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [219]:
x[np.array([0, 2, 4]), np.array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [220]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [221]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [222]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [229]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [223]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [224]:
a[np.arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [225]:
a[np.arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [226]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [227]:
a[np.arange(2, 5)][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])