<a href="https://colab.research.google.com/github/hojun-code/2026-BDA/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [9]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [10]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [11]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [12]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [13]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [14]:
np.column_stack == np.hstack

False

In [15]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [17]:
np.row_stack((a, b))

/tmp/ipykernel_6427/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [18]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [19]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [20]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [21]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [22]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [24]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [25]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [26]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [27]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [28]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [29]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [30]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [31]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [35]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [36]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [38]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [39]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [40]:
ax0.shape

(3, 2, 3)

In [41]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [43]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [45]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [46]:
ax1.shape

(2, 3, 3)

In [47]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [49]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [50]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [51]:
ax2.shape

(2, 3, 3)

In [52]:
print(x, '\n')
print(y, '\n')
print(z, '\n')

[[0 1 2]
 [3 4 5]] 

[[10 11 12]
 [13 14 15]] 

[[20 21 22]
 [23 24 25]] 



In [53]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [54]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [56]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [57]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [58]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [59]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [60]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [61]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [62]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [63]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [65]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
c = np.array([1, 3, 5])
c

array([1, 3, 5])

In [67]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [68]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [69]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [71]:
np.row_stack((a, b))

/tmp/ipykernel_6427/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [72]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [75]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [78]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [79]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [80]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [81]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [82]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [83]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [84]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [85]:
np.row_stack((a, b))

/tmp/ipykernel_6427/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [87]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [88]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [89]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [90]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [92]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [93]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [94]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [98]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [96]:
np.r_['0, 2', [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
np.r_['0, 3', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [99]:
arr = np.array([1, 2, 3])
print(arr[np.newaxis, :])
print(arr[np.newaxis, :].shape, '\n')
print(arr[:, np.newaxis])
print(arr[:, np.newaxis].shape)

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1)


In [100]:
np.expand_dims(arr, 0)

array([[1, 2, 3]])

In [101]:
np.expand_dims(arr, 1)

array([[1],
       [2],
       [3]])

In [102]:
np.r_[[1, 2, 3], [4, 5, 6]]

array([1, 2, 3, 4, 5, 6])

In [103]:
np.r_['0, 2, 0', [1, 2, 3], [4, 5, 6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [104]:
np.r_['1, 2, 0', [1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [105]:
np.r_['0, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
np.r_['1, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3, 4, 5, 6]])

In [107]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [108]:
print(np.expand_dims(a, axis=(0, 1)))
print(np.expand_dims(a, axis=(0, 1)).shape)

[[[1 2 3]]]
(1, 1, 3)


In [109]:
print(np.expand_dims(a, axis=(0, 2)))
print(np.expand_dims(a, axis=(0, 2)).shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [110]:
print(np.expand_dims(a, axis=(1, 2)))
print(np.expand_dims(a, axis=(1, 2)).shape)

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)


In [111]:
np.expand_dims(np.array([1,2,3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [112]:
np.expand_dims(np.array([4,5,6]), axis=(1, 2))

array([[[4]],

       [[5]],

       [[6]]])

In [113]:
np.r_['0, 3, 0', [1,2,3], [4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [114]:
np.r_['0, 3, 0', [1,2,3], [4,5,6]].shape

(6, 1, 1)

In [115]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [116]:
print(np.expand_dims(np.array([1,2,3]), axis=(0,2)))
print(np.expand_dims(np.array([4,5,6]), axis=(0,2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [117]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]].shape

(2, 3, 1)

In [118]:
np.r_['0, 3, 2', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [119]:
print(np.expand_dims(np.array([1,2,3]), axis=(0,1)))
print(np.expand_dims(np.array([4,5,6]), axis=(0,1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [120]:
np.r_['0, 3, 2', [1,2,3], [4,5,6]].shape

(2, 1, 3)

In [121]:
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [122]:
type(a)

numpy.matrix

In [123]:
b = np.matrix([[1, 3], [3, 2]])
b

matrix([[1, 3],
        [3, 2]])

In [124]:
a * b

matrix([[ 7,  7],
        [15, 17]])

In [125]:
a @ b

matrix([[ 7,  7],
        [15, 17]])

In [126]:
print(np.r_[[[1,2,3]], [[4,5,6]]])

np.r_['r', [[1,2,3]], [[4,5,6]]]

[[1 2 3]
 [4 5 6]]


matrix([[1, 2, 3],
        [4, 5, 6]])

In [127]:
np.r_['c', [[1,2,3]], [[4,5,6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [129]:
print(np.r_[[1,2,3], [4, 5, 6]])
np.r_['r', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [130]:
print(np.r_[[1,2,3], [4,5,6]])
np.r_['c', [1,2,3], [4,5,6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [131]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [132]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [133]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [134]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [135]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [136]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [137]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
np.row_stack((a, b))

/tmp/ipykernel_6427/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [142]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [143]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [144]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [145]:
np.concatenate((a[:, np.newaxis], b[:, np.newaxis]), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [146]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [147]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [148]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [149]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [150]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [153]:
a = np.arange(24).reshape(2, 12)

In [154]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [155]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [156]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [157]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [158]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [159]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [160]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [161]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [162]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [163]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [164]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [166]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [167]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [168]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [169]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [170]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [171]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [172]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [173]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [174]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [175]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [176]:
a[:1, :]

array([[0, 1, 2]])

In [177]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [178]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [180]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [181]:
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [182]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [183]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [184]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [185]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [186]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [187]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [188]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [189]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [190]:
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [191]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [192]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [193]:
x = np.arange(9.0)

In [194]:
np.array_split(x, 2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [195]:
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [196]:
np.array_split(x, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [197]:
np.array_split(x, 5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [198]:
np.array_split(x, [2, 4, 8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

In [199]:
a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [200]:
np.array_split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [201]:
np.array_split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [202]:
a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [203]:
np.array_split(a, [2, 4], axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [204]:
np.array_split(a, [2, 4], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [205]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [206]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [207]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [208]:
np.dsplit(x, 2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [209]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [210]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [211]:
np.dsplit(x, 4)

ValueError: array split does not result in an equal division

In [212]:
np.dsplit(x, [2, 4, 5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

## 난수 기초와 생성

In [213]:
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7A5ED7DD6A40

In [214]:
r = rg.random()
r

0.22733602246716966

In [215]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [216]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [217]:
rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [218]:
rg.integers(1, 7, (3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [219]:
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [220]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])